# Copyright (c) 2016 Jason McVetta.
#
# This is Free Software, released under the terms of the Apache v2 license.
# See http://www.apache.org/licenses/LICENSE-2.0 for details.
#
# Resist intellectual serfdom.  The ownership of ideas is akin to slavery.
---

- name: Ensure Elastic GPG key is added
  apt_key:
    url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
    state: present


- name: Ensure Beats repository is added
  apt_repository:
    repo: "deb https://packages.elastic.co/beats/apt stable main"
    update_cache: yes
    state: present


- name: Ensure Filebeat is installed
  apt:
    name: filebeat
    state: present


- name: Ensure Filebeat is configured
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify: restart filebeat


- name: Ensure Filebeat is started and enabled on boot
  service:
    name: filebeat
    enabled: yes
    state: started


- include: topbeat.yml
  notify: restart filebeat
  when: logzio_topbeat

- include: packetbeat.yml
  notify: restart filebeat
  when: logzio_packetbeat

