---
# handlers file for mediapeers.filebeat

- name: restart filebeat
  service:
    name: filebeat
    state: restarted

- name: restart topbeat
  service:
    name: topbeat
    state: restarted

- name: restart packetbeat
  service:
    name: packetbeat
    state: restarted

